apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password  
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-service
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
#     service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0 # specify internal
# spec:
#   selector:
#     app: mongo
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetPort: 27017