# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: webapp-deployment
#   labels:
#     app: webapp
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: webapp
#   template:
#     metadata:
#       labels:
#         app: webapp
#     spec:
#       containers:
#       - name: webapp
#         image: testaccount007/demo:v1.0 # nanajanashia/k8s-demo-app:v1.0 #
#         # imagePullPolicy: "Always"
#         ports:
#         - containerPort: 30100
#         # startupProbe:
#         #   exec:
#         #     command:
#         #     - sleep
#         #     - "5"
#         #   initialDelaySeconds: 20
#         #   periodSeconds: 20
#         env:
#         - name: USER_NAME
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-user
#         - name: USER_PWD
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-password 
#         - name: DB_URL
#           valueFrom:
#             configMapKeyRef:
#               name: mongo-config
#               key: mongo-url
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webapp-service
# spec:
#   type: NodePort
#   selector:
#     app: webapp
#   ports:
#     - protocol: TCP
#       port: 30100
#       targetPort: 30100
#       nodePort: 30100
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: webapp-service
# #   annotations:
# #     service.beta.kubernetes.io/aws-load-balancer-type: nlb
# #     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
# # spec:
# #   selector:
# #     app: webapp
# #   type: LoadBalancer
# #   ports:
# #     - protocol: TCP
# #       port: 3000
# #       targetPort: 3000



apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
          name: http-web-svc
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: http-web-svc
      nodePort: 30100